# 配置tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9999
  connection-timeout: 5000ms
# 配置spring
spring:
  application:
    name: dubbo-demo-provider
# Dubbo 配置文件
dubbo:
  application:
    name: dubbo-demo-provider
  registry:
    address: 10.100.2.163:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.example.demo.dubbodemoprovider.service
# 配置日志
logging:
  config: classpath:log4j2-spring.xml
